# Generated by Django 6.1.1 on 2026-10-05 10:07

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('location_type', models.CharField(choices=[('Research Station', 'Research Station'), ('Expedition Camp', 'Expedition Camp'), ('Storage Facility', 'Storage Facility'), ('Supply Point', 'Supply Point'), ('Field Location', 'Field Location')], default='Research Station', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='operations.location')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Snowmobile', 'Snowmobile'), ('Generator', 'Generator'), ('Satellite Phone', 'Satellite Phone'), ('GPS Device', 'GPS Device'), ('Research Equipment', 'Research Equipment'), ('Heating System', 'Heating System'), ('Communication Equipment', 'Communication Equipment'), ('Protective Gear', 'Protective Gear'), ('Vehicle', 'Vehicle'), ('Other', 'Other')], default='Other', max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Under Maintenance', 'Under Maintenance'), ('Damaged', 'Damaged'), ('Retired', 'Retired')], default='Available', max_length=30)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operations.expedition')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='operations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=50, unique=True)),
                ('item_description', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('transport_method', models.CharField(choices=[('Ski-Plane Air Drop', 'Ski-Plane Air Drop'), ('Twin Otter Cargo Flight', 'Twin Otter Cargo Flight'), ('Icebreaker Vessel', 'Icebreaker Vessel'), ('Snowcat Overland Convoy', 'Snowcat Overland Convoy'), ('Helicopter Sling', 'Helicopter Sling'), ('Snowmobile Sled', 'Snowmobile Sled')], default='Twin Otter Cargo Flight', max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_records', to='operations.expedition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=50, unique=True)),
                ('maintenance_type', models.CharField(choices=[('Scheduled Service', 'Scheduled Service'), ('Pre-Departure Inspection', 'Pre-Departure Inspection'), ('Cold-Weather Overhaul', 'Cold-Weather Overhaul'), ('Emergency Repair', 'Emergency Repair'), ('Calibration', 'Calibration')], default='Scheduled Service', max_length=50)),
                ('description', models.TextField()),
                ('maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Scheduled', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='operations.asset')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Expedition Leader', 'Expedition Leader'), ('Researcher', 'Researcher'), ('Engineer', 'Engineer'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Medical Officer', 'Medical Officer'), ('Technician', 'Technician')], default='Researcher', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='operations.expedition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Medical Supplies', 'Medical Supplies'), ('Water', 'Water'), ('Batteries', 'Batteries'), ('Research Materials', 'Research Materials'), ('Emergency Equipment', 'Emergency Equipment'), ('Other', 'Other')], default='Other', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='Units', max_length=50)),
                ('minimum_required_quantity', models.PositiveIntegerField(default=10)),
                ('storage_location', models.CharField(blank=True, max_length=150)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='operations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.personnel')),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.expedition')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
